### ISSUE TITLE
Where do I find and change the cloudstore.properties file location?

### ISSUE THREAD

**Issue by ironjohn** [cloudstore/cloudstore#49]
Where do I find and change the cloudstore.configDir system property?

I am testing cloudstore on Windows, Mac, and Ubuntu to sync the same directory in the same location on all systems.  My life would be much easier if any customization were always in the same place regardless of the user ID currently logged in to the system.

**Comment by nlmarco** [comment]
Like every Java system property, it can optionally be passed as command-line-argument to the java command.

You have to add:

-Dcloudstore.configDir=/some/directory

The java command is inside the cloudstore / cloudstore.bat shell/batch script.

Now that you raise the topic, I think we should add the possibility to specify an OS environment variable (so that the shell/batch script does not need to be modified). This currently does not yet exist. Sorry.

**Comment by nlmarco** [comment]
Just wanted to add:

Currently, there is the following command:

java -jar "$INSTALLATION_DIR/lib/${project.artifactId}-${project.version}.jar" "$@"

or:

java -jar "%~dp0\..\lib\${project.artifactId}-${project.version}.jar" %*

The system properties need to be added at the beginning. That means, you'll need to change them to sth. like this:

java -Dcloudstore.configDir=/some/directory -jar "$INSTALLATION_DIR/lib/${project.artifactId}-${project.version}.jar" "$@"

or:

java -Dcloudstore.configDir=C:/drive/letters/are/bullshit -jar "%~dp0\..\lib\${project.artifactId}-${project.version}.jar" %*

Note that you can AFAIK use both in Windows: / or \ (because even the Windows C API internally supports "/" - only the plain cmd does not)

**Comment by nlmarco** [comment]
Since version 0.9.7, it is possible to set every configuration property not only as system property, but also as environment setting.

Since the operating system's environment variables do not allow dots in their names (at least not in GNU/Linux), I use underscores instead of dots. The same applies to index-brackets ("[" and "]").

This means, to set the configuration directory, either set "cloudstore.configDir" as system property (as documented above) or set "cloudstore_configDir" as environment variable.

The priorities (or override-rules) are as follows:
* A system-property has the highest priority.
* Followed by an environment variable.
* And last is the configuration done in the config-files (cloudstore-properties).

Furthermore, I made it possible to pass system-properties as real (main) arguments. This means, it's not necessary anymore to modify the shell (or bat) script. Instead, "-Dxxxx=yyyy" may be passed as normal parameter. For example:

`cloudstore -Dcloudstore.configDir=/some/directory`

or

`~/bin/cloudstore/bin/cloudstore -Dcloudstore.configDir=/some/directory`

works too.
